In [3]:
import numpy as np

a=np.random.randn(3,3) # a.shape = (3, 3)a.shape=(3,3)

b=np.random.randn(2,1) #  b.shape = (2, 1)b.shape=(2,1)

c = a + b

ValueError: operands could not be broadcast together with shapes (3,3) (2,1) 

In [6]:
a=np.random.randn(4,3) # a.shape = (3, 3)a.shape=(3,3)
print("a: ", a)
b=np.random.randn(1,3) #  b.shape = (2, 1)b.shape=(2,1)
print("b: ", b)
c = a * b
print("c: ", c)

a:  [[ 0.06595392 -1.7984665   0.84151778]
 [ 2.22904668 -0.20626345 -1.73003425]
 [-0.48563321 -0.58055589 -0.19225134]
 [-0.30093734  0.23323286  0.06404683]]
b:  [[0.2083579  0.52286792 0.38004608]]
c:  [[ 0.01374202 -0.94036044  0.31981553]
 [ 0.46443948 -0.10784854 -0.65749274]
 [-0.10118551 -0.30355405 -0.07306437]
 [-0.06270267  0.12194998  0.02434075]]


In [7]:
a = np.array([[2,1],[1,3]])
a*a

array([[4, 1],
       [1, 9]])