This is an exercise notebook to get familiar with numpy, following the course "Neural Networks and Deep Learning" on [coursera](https://www.coursera.org/learn/neural-networks-deep-learning/home/welcome).

### 1. Numpy generates 1D array

also called rank 1 array

In [1]:
import numpy as np

a = np.random.randn(5)
print(a)
print(a.shape)

[-0.37592337 -0.43339369  1.76635435  0.95888308 -0.50306065]
(5,)


In [2]:
print(a.T)
print(np.dot(a,a.T))

[-1.00241989 -1.08260619 -1.56788542 -0.55195003 -0.50699826]
5.196842557422108


Above shows that `np.random.randn(5)` generates 1D array. 

Note that the output only has one bracket.

In [9]:
a.reshape(1,5)

array([[-1.00241989, -1.08260619, -1.56788542, -0.55195003, -0.50699826]])

### 2. Numpy generates 2D array

In [4]:
b = np.random.randn(1,5)
b

array([[-0.43069887, -1.3277467 , -0.75176536, -0.3500037 , -0.77488793]])

Generate a 1x5 vector with two brackets.

In [5]:
print(b.shape)
print(b.T)

(1, 5)
[[-0.43069887]
 [-1.3277467 ]
 [-0.75176536]
 [-0.3500037 ]
 [-0.77488793]]


In [7]:
print(np.dot(b,b.T)) # row vector x column vector -> a number
print(np.dot(b.T,b)) # column vector x row vector -> matrix (5x5)

[[3.23651787]]
[[0.18550152 0.571859   0.32378449 0.1507462  0.33374336]
 [0.571859   1.7629113  0.99815397 0.46471626 1.0288549 ]
 [0.32378449 0.99815397 0.56515115 0.26312066 0.58253391]
 [0.1507462  0.46471626 0.26312066 0.12250259 0.27121365]
 [0.33374336 1.0288549  0.58253391 0.27121365 0.60045131]]


In [3]:
x=np.array([[[1],[2]],[[3],[4]]])
print(x)
print(x.shape)

[[[1]
  [2]]

 [[3]
  [4]]]
(2, 2, 1)


In [5]:
a = np.random.randn(4,3)
print(a)
b = np.random.randn(3,2)
print(b)
c = a * b
print(c)

[[-0.60720127  0.74287072 -0.59497666]
 [-1.38340971  0.19803342  0.12986393]
 [-0.88266485  0.00473806 -0.0882346 ]
 [ 0.03627723  0.37090075 -0.27854052]]
[[-0.62314518 -0.61885825]
 [-1.42099207  0.92611359]
 [-0.87150679 -1.06509258]]


ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [6]:
a=np.array([[2,1],[1,3]])
a

array([[2, 1],
       [1, 3]])

In [7]:
a*a

array([[4, 1],
       [1, 9]])

In [9]:
#a.shape=(3,4)
a = np.random.randn(3,4)
print("a: ", a)
#b.shape = (4, 1)
b = np.random.randn(4,1)
print("b: ", b)

c =[]

for i in range(3):
    for j in range(4):
        c[i][j] = a[j][i] + b[j]
print(c)

a:  [[ 0.29167681 -1.46817472  0.98655712  0.27485644]
 [ 0.35813651  0.19186438 -0.41402889  0.05826587]
 [ 0.47201947  0.58598561 -0.08648238 -1.32827508]]
b:  [[-0.12299482]
 [-0.93906154]
 [ 1.12600681]
 [ 0.52610002]]


IndexError: list index out of range